export const GET_SUBJECTS = 'GET_SUBJECTS';
export const GET_SUBJECT = 'GET_SUBJECT';
export const CREATE_SUBJECT = 'CREATE_SUBJECT';
export const UPDATE_SUBJECT = 'UPDATE_SUBJECT';
export const DELETE_SUBJECT = 'DELETE_SUBJECT';
export const SUBJECTS_ERROR = 'SUBJECTS_ERROR';


export const GET_FACULTY = 'GET_FACULTY';
export const CREATE_FACULTY = 'CREATE_FACULTY';
export const UPDATE_FACULTY = 'UPDATE_FACULTY';
export const DELETE_FACULTY = 'DELETE_FACULTY';
export const FACULTY_ERROR = 'FACULTY_ERROR';